[package]
name = "event_derive"
authors.workspace = true
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dev-dependencies]
gene = { path = "../gene" }

[dependencies]
proc-macro2 = "1.0.69"
quote = "1.0.33"
syn = { version = "2.0.39", features = ["full"] }
